### ISSUE TITLE
Training data appears to be behind paywall, not "freely available"

### ISSUE THREAD

**Issue by bencomp** [OCR-D/ocrd_typegroups_classifier#9]
Whereas the README says the training data is freely available, the ACM DL asks me to login or pay to get access. That is not what I expected. Could you clarify what you meant and perhaps provide other means to the training data?

**Comment by kba** [comment]
If I am not mistaken, that dataset is also published at https://zenodo.org/record/3366686 @seuretm @VChristlein ?

**Comment by VChristlein** [comment]
Exactly, the paper is also freely accessible at http://www.weichselbaumer.info/s/HIP2019_type_groups_dataset.pdf
